version: '3'

tasks:
    update-brew:
        cmds:
            - brew update && brew upgrade && brew cleanup || true
    setup:
        desc: Setup the project dependencies
        cmds:
            - task: update-brew
            - command -v pnpm &> /dev/null || brew install pnpm
            - command -v openapi-generator &> /dev/null || brew install openapi-generator
            - pnpm install
    update:
        desc: Update the project dependencies
        cmds:
            - task: update-brew
            - pnpm add -g pnpm && pnpm update --latest
    generate:ebay-client:
        desc: Generate the eBay API client
        cmds:
            - rm -rf gen/ebay || true
            - openapi-generator generate -i https://developer.ebay.com/api-docs/master/buy/browse/openapi/3/buy_browse_v1_oas3.yaml -o "gen/ebay" -g typescript-fetch --additional-properties=importFileExtension=.js
