POST http://localhost:7071/api/whatsapp-webhook
Content-Type: application/json

{
  "object": "whatsapp_business_account",
  "entry": [
    {
      "id": "240586499133002",
      "changes": [
        {
          "value": {
            "messaging_product": "whatsapp",
            "metadata": {
              "display_phone_number": "14844145978",
              "phone_number_id": "246419355213038"
            },
            "contacts": [
              {
                "profile": { "name": "Naaman Hirschfeld" },
                "wa_id": "4915731800813"
              }
            ],
            "messages": [
              {
                "from": "4915731800813",
                "id": "wamid.HBgNNDkxNTczMTgwMDgxMxUCABIYFDNBQTdCODIwQjQ4RUI1NzcyRjY0AA==",
                "timestamp": "1708340381",
                "text": {
                  "body": "hi, please recommend a laptop for a 10 year old. Not too expensive"
                },
                "type": "text"
              }
            ]
          },
          "field": "messages"
        }
      ]
    }
  ]
}

###

POST https://basemind.azurewebsites.net/api/whatsapp-webhook
Content-Type: application/json

{
  "object": "whatsapp_business_account",
  "entry": [
    {
      "id": "240586499133002",
      "changes": [
        {
          "value": {
            "messaging_product": "whatsapp",
            "metadata": {
              "display_phone_number": "14844145978",
              "phone_number_id": "246419355213038"
            },
            "contacts": [
              {
                "profile": { "name": "Naaman Hirschfeld" },
                "wa_id": "4915731800813"
              }
            ],
            "messages": [
              {
                "from": "4915731800813",
                "id": "wamid.HBgNNDkxNTczMTgwMDgxMxUCABIYFDNBQTdCODIwQjQ4RUI1NzcyRjY0AA==",
                "timestamp": "1708340381",
                "text": {
                  "body": "hi, please recommend a laptop for a 10 year old. Not too expensive"
                },
                "type": "text"
              }
            ]
          },
          "field": "messages"
        }
      ]
    }
  ]
}

###

GET https://basemind.azurewebsites.net/api/whatsapp-webhook?hub.verify_token=a4fb990c-39e0-4726-a06c-050a6b7861f3&hub.challenge=CHALLENGE_ACCEPTED&hub.mode=subscribe
