name: Deploy

on:
    push:
        branches:
            - main
    workflow_dispatch:

env:
    AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # set this to the path to your web app project, defaults to the repository root
    NODE_VERSION: '20.x' # set this to the node version to use (supports 8.x, 10.x, 12.x)

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: 'npm'
            - name: Install
              run: npm install
            - name: Build
              run: npm run build
            - name: Prune
              run: npm prune --production
            - name: 'Deploy'
              uses: Azure/functions-action@v1
              id: fa
              with:
                  app-name: 'basemind'
                  slot-name: 'Production'
                  package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
                  publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A7255E6476824DE98D260EF05A2F03EB }}
